import { getSupabase } from '@/lib/supabase';
import { getGmail } from '@/lib/gmail';
import { getConfig } from '@/lib/config';
import { buildRawEmail } from '@/lib/email-builder';
import { sendSlackMessage } from '@/lib/slack';
import { createChildLogger } from '@/lib/logger';

const log = createChildLogger('digest');

export async function sendDailyDigest(): Promise<void> {
  const supabase = getSupabase();

  // Query 24h stats
  const { data: stats } = await supabase.rpc('get_24h_stats').select('*');

  // Fallback: raw query if RPC not available
  const { data: statsRaw } = await supabase
    .from('email_cases')
    .select('status, intent, urgency_level')
    .gte('received_at', new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString());

  // Query stuck items
  const { data: stuckItems } = await supabase
    .from('email_cases')
    .select('id, customer_name, customer_email, intent, urgency_level, status, received_at, updated_at')
    .or(
      'and(status.eq.RECEIVED,received_at.lt.' + hoursAgo(0.17) + '),' +
      'and(status.eq.CLASSIFIED,updated_at.lt.' + hoursAgo(0.17) + '),' +
      'and(status.eq.RESPONDED_PENDING_BOOKING,updated_at.lt.' + hoursAgo(48) + '),' +
      'and(status.eq.NEEDS_REVIEW,updated_at.lt.' + hoursAgo(24) + '),' +
      'and(status.eq.NEEDS_MANUAL_CALL,updated_at.lt.' + hoursAgo(24) + ')'
    )
    .order('received_at', { ascending: true });

  const cases = statsRaw || stats || [];
  const stuck = stuckItems || [];

  // Aggregate stats
  const statusCounts: Record<string, number> = {};
  const intentCounts: Record<string, number> = {};
  const urgencyCounts: Record<string, number> = {};

  for (const row of cases) {
    statusCounts[row.status] = (statusCounts[row.status] || 0) + 1;
    if (row.intent) intentCounts[row.intent] = (intentCounts[row.intent] || 0) + 1;
    if (row.urgency_level) urgencyCounts[row.urgency_level] = (urgencyCounts[row.urgency_level] || 0) + 1;
  }

  const totalCases = cases.length;
  const now = new Date().toLocaleString('en-US', { timeZone: 'America/Chicago' });

  const [businessName] = await Promise.all([
    getConfig<string>('business_name', 'ProFix Electric & Plumbing'),
  ]);

  const divider = '='.repeat(50);
  const subDivider = '-'.repeat(40);

  let digest = `
${divider}
  DAILY OPERATIONS DIGEST
  ${now}
${divider}

LAST 24 HOURS: ${totalCases} total cases

BY STATUS:
${formatCounts(statusCounts)}

BY INTENT:
${formatCounts(intentCounts)}

BY URGENCY:
${formatCounts(urgencyCounts)}
`;

  if (stuck.length > 0) {
    digest += `\n\n*** STUCK ITEMS (${stuck.length}) — NEEDS ATTENTION ***\n${subDivider}\n`;
    for (const item of stuck) {
      const ageMinutes = Math.round((Date.now() - new Date(item.received_at).getTime()) / 60000);
      const ageLabel = ageMinutes > 60
        ? `${Math.floor(ageMinutes / 60)}h ${ageMinutes % 60}m`
        : `${ageMinutes}m`;
      digest += `  #${item.id} | ${(item.status || '').padEnd(25)} | ${(item.urgency_level || '').padEnd(10)} | ${(item.customer_name || 'Unknown').padEnd(20)} | Age: ${ageLabel}\n`;
    }
    digest += `\n  ACTION REQUIRED: Please review stuck items in the dashboard.\n`;
  } else {
    digest += `\n\nNo stuck items — all clear!\n`;
  }

  digest += `\n${subDivider}\nGenerated by ServiceFlow\nBusiness: ${businessName}`;

  const emailSubject = `[${businessName}] Daily Ops Digest — ${totalCases} cases | ${stuck.length} stuck`;

  // Send digest email
  const ownerEmail = await getConfig<string>('owner_email', '');
  if (ownerEmail) {
    try {
      const gmail = getGmail();
      const sendAs = process.env.GMAIL_SEND_AS || '';
      const rawMessage = buildRawEmail({ to: ownerEmail, from: sendAs, subject: emailSubject, text: digest });
      await gmail.users.messages.send({ userId: 'me', requestBody: { raw: rawMessage } });
      log.info('Digest email sent');
    } catch (err) {
      log.error({ err }, 'Failed to send digest email');
    }
  }

  // Send Slack alert if stuck items exist
  if (stuck.length > 0) {
    await sendSlackMessage(
      `*Daily Digest Alert*\n${stuck.length} stuck items need attention.\nTotal cases (24h): ${totalCases}\n\nCheck email for full digest.`,
    );
  }

  log.info({ totalCases, stuckCount: stuck.length }, 'Daily digest complete');
}

export async function sendErrorAlert(params: {
  queueName: string;
  jobId: string;
  errorMessage: string;
  timestamp: string;
}): Promise<void> {
  const slackMsg = `*ServiceFlow Worker Error*\nQueue: ${params.queueName}\nJob: ${params.jobId}\nError: ${params.errorMessage.substring(0, 200)}\nTime: ${params.timestamp}`;

  await sendSlackMessage(slackMsg);

  // Also send email alert
  const ownerEmail = await getConfig<string>('owner_email', '');
  if (ownerEmail) {
    try {
      const gmail = getGmail();
      const sendAs = process.env.GMAIL_SEND_AS || '';
      const subject = `[ServiceFlow ERROR] ${params.queueName} — ${params.jobId}`;
      const body = `ServiceFlow WORKER ERROR
${'='.repeat(40)}

Queue:       ${params.queueName}
Job ID:      ${params.jobId}
Timestamp:   ${params.timestamp}

Error Message:
${params.errorMessage}

Please check the ServiceFlow dashboard for details.`;

      const rawMessage = buildRawEmail({ to: ownerEmail, from: sendAs, subject, text: body });
      await gmail.users.messages.send({ userId: 'me', requestBody: { raw: rawMessage } });
    } catch (err) {
      log.error({ err }, 'Failed to send error alert email');
    }
  }

  log.warn(params, 'Error alert sent');
}

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

function formatCounts(counts: Record<string, number>): string {
  const entries = Object.entries(counts);
  if (entries.length === 0) return '  (no data)';
  return entries.map(([k, v]) => `  ${k.padEnd(30)} ${v}`).join('\n');
}
